import { GameGenre } from './types.ts';

export const gameGenres: GameGenre[] = [
	'Action',
	'Adventure',
	'Role-Playing',
	'Simulation',
	'Strategy',
	'Sports',
	'Puzzle',
	'Idle',
	'Platformer',
	'Fighting',
	'Racing',
	'Shooter',
	'Stealth',
	'Survival',
	'Horror',
	'Sandbox',
	'Massively Multiplayer Online',
	'Battle Royale',
	'Card',
	'Rhythm',
	'Trivia',
	'Turn-Based Strategy',
	'Real-Time Strategy',
	'Tower Defense',
	'Text-Based',
	'Open World',
	'Metroidvania',
	'Rogue-like',
	'Rogue-lite',
	'Bullet Hell',
	'Interactive Story',
	'Educational',
	'Social Simulation',
	'Music',
	'Party',
	'Visual Novel',
	'Dating Sim',
	'Tactical',
	'Hack and Slash',
	'MMORPG',
	'MOBA',
	'Puzzle-Platformer',
	'Vehicular Combat',
	'Battle Racing',
	'Beat ‘em up',
	'Tycoon',
	'Board Game',
	'Deckbuilding',
	'Arcade',
	'Survival Horror',
	'Action-Adventure',
	'First-Person Shooter',
	'Third-Person Shooter',
	'Pinball',
	'Dungeon Crawler',
	'Rogue-lite'
];
